disabled_rules:
  - multiple_closures_with_trailing_closure
  - empty_parentheses_with_trailing_closure
  - identifier_name
  - unused_optional_binding
  - line_length
  - function_parameter_count
  - syntactic_sugar
  - implicit_getter
  - todo
  - weak_delegate
  - cyclomatic_complexity
  - void_return
  - legacy_hashing
  - function_body_length
  - valid_ibinspectable
  - orphaned_doc_comment

file_length:
  warning: 1000
  error: 1200

force_cast: error

type_body_length:
  warning: 300
  error: 500
