name: PR
on:
  push:
    branches: [ main ]

jobs:
  swiftlint:
    name: "MarvelApp: tests"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gem install
        run:  bundle install
      - name: Swiftlint
        run: 'swiftlint --strict'
      - name: Run tests
        run: bundle exec fastlane tests
      - name: Run xcov
        run: bundle exec xcov --output_directory 'xcov_output/' -x '.xcovignore'
      - name: Upload XCOV report
        uses: actions/upload-artifact@v1
        with:
          name: XCOV report
          path: xcov_output/
