name: PR
on:
  push:
    branches: [ main ]

jobs:
  swiftlint:
    name: "MarvelApp: tests"
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gem install
        run:  bundle install
      - name: Swiftlint
        run: 'swiftlint --strict'
      - name: Run tests
        run: bundle exec fastlane tests
